package image

import (
	"bytes"
	"compress/flate"
	"compress/lzw"
	"compress/zlib"
	"image"
	"image/color"
	"image/jpeg"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	domainimage "github.com/dh-kam/pdf-go/internal/domain/image"
)

type stubDecoder struct {
	wasUsed bool
}

func (s *stubDecoder) Decode(data []byte) (image.Image, error) {
	s.wasUsed = true
	return image.NewRGBA(image.Rect(0, 0, 1, 1)), nil
}

func (s *stubDecoder) DecodeConfig(_ []byte) (image.Config, error) {
	return image.Config{Width: 1, Height: 1}, nil
}

func (s *stubDecoder) ColorSpace() domainimage.ColorSpace {
	return domainimage.ColorSpaceDeviceRGB
}

func TestDecoder_NewDecoder_RegistersDefaultCodecs(t *testing.T) {
	d := NewDecoder()
	require.NotNil(t, d)

	// JPEG codec should be available by default.
	_, err := d.Decode(&domainimage.ImageData{
		Filter:           domainimage.FilterDCT,
		Data:             jpegTestData(t),
		Width:            1,
		Height:           1,
		BitsPerComponent: 8,
		ColorSpace:       domainimage.ColorSpaceDeviceRGB,
	})
	require.NoError(t, err)
}

func TestDecoder_DecodeNilData(t *testing.T) {
	d := NewDecoder()
	_, err := d.Decode(nil)
	require.Error(t, err)
}

func TestDecoder_UsesProvidedColorSpaceForDCT(t *testing.T) {
	d := NewDecoder()
	img, err := d.Decode(&domainimage.ImageData{
		Filter:           domainimage.FilterDCT,
		Data:             jpegTestGrayData(t),
		Width:            1,
		Height:           1,
		BitsPerComponent: 8,
		ColorSpace:       domainimage.ColorSpaceDeviceGray,
	})
	require.NoError(t, err)
	require.NotNil(t, img)
	assert.Equal(t, domainimage.ColorSpaceDeviceGray, img.ColorSpace())
}

func TestDecoder_DecodeGrayImage(t *testing.T) {
	d := NewDecoder()
	img, err := d.Decode(&domainimage.ImageData{
		Filter:           domainimage.FilterNone,
		Data:             []byte{0x80},
		Width:            1,
		Height:           1,
		BitsPerComponent: 8,
		ColorSpace:       domainimage.ColorSpaceDeviceGray,
	})
	require.NoError(t, err)
	require.NotNil(t, img)
	assert.Equal(t, 1, img.Width())
	assert.Equal(t, 1, img.Height())
	assert.Equal(t, domainimage.ColorSpaceDeviceGray, img.ColorSpace())

	gray, ok := img.Image().(*image.Gray)
	require.True(t, ok)
	assert.Equal(t, uint8(0x80), gray.GrayAt(0, 0).Y)
}

func TestParseBinaryPPMWithComments(t *testing.T) {
	img, err := parseBinaryPPM([]byte("P6\n# generated by decoder\n2 1\n255\n\x01\x02\x03\x04\x05\x06"))
	require.NoError(t, err)

	rgba, ok := img.(*image.RGBA)
	require.True(t, ok)
	assert.Equal(t, color.RGBA{R: 1, G: 2, B: 3, A: 255}, rgba.RGBAAt(0, 0))
	assert.Equal(t, color.RGBA{R: 4, G: 5, B: 6, A: 255}, rgba.RGBAAt(1, 0))
}

func TestParseBinaryPGMWithComments(t *testing.T) {
	img, err := parseBinaryPGM([]byte("P5\n# generated by decoder\n2 1\n255\n\x01\x02"))
	require.NoError(t, err)

	gray, ok := img.(*image.Gray)
	require.True(t, ok)
	assert.Equal(t, uint8(1), gray.GrayAt(0, 0).Y)
	assert.Equal(t, uint8(2), gray.GrayAt(1, 0).Y)
}

func TestDecoder_DecodeFlateWithDecompressedData(t *testing.T) {
	var compressed bytes.Buffer
	w := zlib.NewWriter(&compressed)
	_, err := w.Write([]byte{0x10, 0x20, 0x30, 0x40})
	require.NoError(t, err)
	require.NoError(t, w.Close())

	d := NewDecoder()
	img, err := d.Decode(&domainimage.ImageData{
		Filter:           domainimage.FilterFlate,
		Data:             compressed.Bytes(),
		Width:            2,
		Height:           2,
		BitsPerComponent: 8,
		ColorSpace:       domainimage.ColorSpaceDeviceGray,
	})
	require.NoError(t, err)

	gray, ok := img.Image().(*image.Gray)
	require.True(t, ok)
	assert.Equal(t, []byte{0x10, 0x20, 0x30, 0x40}, gray.Pix)
}

func TestDecoder_DecodeFlateFallbackToRawDeflate(t *testing.T) {
	var compressed bytes.Buffer
	fw, err := flate.NewWriter(&compressed, flate.BestSpeed)
	require.NoError(t, err)

	payload := []byte{0x10, 0x20, 0x30, 0x40}
	_, err = fw.Write(payload)
	require.NoError(t, err)
	require.NoError(t, fw.Close())

	d := NewDecoder()
	out, err := d.decompress(compressed.Bytes(), domainimage.FilterFlate, nil)
	require.NoError(t, err)
	assert.Equal(t, payload, out)
}

func TestDecoder_DecodeASCIIHexUnsupported(t *testing.T) {
	d := NewDecoder()
	_, err := d.Decode(&domainimage.ImageData{
		Filter:           domainimage.FilterASCIIHex,
		Data:             []byte(""),
		Width:            1,
		Height:           1,
		BitsPerComponent: 8,
		ColorSpace:       domainimage.ColorSpaceDeviceGray,
	})
	assert.Error(t, err)
}

func TestDecoder_DecodeCMYKAndRGBConversions(t *testing.T) {
	d := NewDecoder()

	rgb, err := d.Decode(&domainimage.ImageData{
		Filter:           domainimage.FilterNone,
		Data:             []byte{16, 32, 48},
		Width:            1,
		Height:           1,
		BitsPerComponent: 8,
		ColorSpace:       domainimage.ColorSpaceDeviceRGB,
	})
	require.NoError(t, err)
	rgba, ok := rgb.Image().(*image.RGBA)
	require.True(t, ok)
	assert.Equal(t, color.RGBA{16, 32, 48, 255}, rgba.RGBAAt(0, 0))

	decoded, err := d.Decode(&domainimage.ImageData{
		Filter:           domainimage.FilterNone,
		Data:             []byte{0, 0, 0, 0},
		Width:            1,
		Height:           1,
		BitsPerComponent: 8,
		ColorSpace:       domainimage.ColorSpaceDeviceCMYK,
	})
	require.NoError(t, err)
	rgbaCMYK, ok := decoded.Image().(*image.RGBA)
	require.True(t, ok)
	assert.Equal(t, color.RGBA{255, 255, 255, 255}, rgbaCMYK.RGBAAt(0, 0))
}

func TestDecoder_DecodeIndexedCMYKMatchesDirectCMYKConversion(t *testing.T) {
	d := NewDecoder()

	indexed, err := d.Decode(&domainimage.ImageData{
		Filter:           domainimage.FilterNone,
		Data:             []byte{0x00, 0x01},
		Width:            2,
		Height:           1,
		BitsPerComponent: 8,
		ColorSpace:       domainimage.ColorSpaceIndexed,
		IndexedBase:      domainimage.ColorSpaceDeviceCMYK,
		IndexedLookup: []byte{
			0x00, 0x00, 0x00, 0x00,
			0x00, 0x00, 0x00, 0xFF,
		},
	})
	require.NoError(t, err)

	direct, err := d.Decode(&domainimage.ImageData{
		Filter:           domainimage.FilterNone,
		Data:             []byte{0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF},
		Width:            2,
		Height:           1,
		BitsPerComponent: 8,
		ColorSpace:       domainimage.ColorSpaceDeviceCMYK,
	})
	require.NoError(t, err)

	indexedRGBA, ok := indexed.Image().(*image.RGBA)
	require.True(t, ok)
	directRGBA, ok := direct.Image().(*image.RGBA)
	require.True(t, ok)

	assert.Equal(t, directRGBA.RGBAAt(0, 0), indexedRGBA.RGBAAt(0, 0))
	assert.Equal(t, directRGBA.RGBAAt(1, 0), indexedRGBA.RGBAAt(1, 0))
}

func TestDecoder_DecodeIndexedCMYKHonorsDecodeArray(t *testing.T) {
	d := NewDecoder()

	indexed, err := d.Decode(&domainimage.ImageData{
		Filter:           domainimage.FilterNone,
		Data:             []byte{0x00, 0x01},
		Width:            2,
		Height:           1,
		BitsPerComponent: 8,
		ColorSpace:       domainimage.ColorSpaceIndexed,
		IndexedBase:      domainimage.ColorSpaceDeviceCMYK,
		IndexedLookup: []byte{
			0x00, 0x00, 0x00, 0x00,
			0x00, 0x00, 0x00, 0xFF,
		},
		Decode: []float64{1, 0},
	})
	require.NoError(t, err)

	direct, err := d.Decode(&domainimage.ImageData{
		Filter:           domainimage.FilterNone,
		Data:             []byte{0x00, 0x00, 0x00, 0xFF, 0x00, 0x00, 0x00, 0x00},
		Width:            2,
		Height:           1,
		BitsPerComponent: 8,
		ColorSpace:       domainimage.ColorSpaceDeviceCMYK,
	})
	require.NoError(t, err)

	indexedRGBA, ok := indexed.Image().(*image.RGBA)
	require.True(t, ok)
	directRGBA, ok := direct.Image().(*image.RGBA)
	require.True(t, ok)

	assert.Equal(t, directRGBA.RGBAAt(0, 0), indexedRGBA.RGBAAt(0, 0))
	assert.Equal(t, directRGBA.RGBAAt(1, 0), indexedRGBA.RGBAAt(1, 0))
	assert.NotEqual(t, indexedRGBA.RGBAAt(0, 0), indexedRGBA.RGBAAt(1, 0))
}

func TestDecoder_DecodeCMYKSimpleSubtractiveConversionMode(t *testing.T) {
	d := NewDecoder()

	img, err := d.Decode(&domainimage.ImageData{
		Filter:             domainimage.FilterNone,
		Data:               []byte{0x00, 0x00, 0x00, 0xFF, 0xFF, 0x00, 0x00, 0x00},
		Width:              2,
		Height:             1,
		BitsPerComponent:   8,
		ColorSpace:         domainimage.ColorSpaceDeviceCMYK,
		CMYKConversionMode: domainimage.CMYKConversionModeSimpleSubtractive,
	})
	require.NoError(t, err)

	rgba, ok := img.Image().(*image.RGBA)
	require.True(t, ok)
	assert.Equal(t, color.RGBA{0, 0, 0, 255}, rgba.RGBAAt(0, 0))
	assert.Equal(t, color.RGBA{0, 255, 255, 255}, rgba.RGBAAt(1, 0))
}

func TestDecoder_DecodeIndexedCMYKSimpleSubtractiveConversionMode(t *testing.T) {
	d := NewDecoder()

	img, err := d.Decode(&domainimage.ImageData{
		Filter:             domainimage.FilterNone,
		Data:               []byte{0x00, 0x01},
		Width:              2,
		Height:             1,
		BitsPerComponent:   8,
		ColorSpace:         domainimage.ColorSpaceIndexed,
		IndexedBase:        domainimage.ColorSpaceDeviceCMYK,
		CMYKConversionMode: domainimage.CMYKConversionModeSimpleSubtractive,
		IndexedLookup: []byte{
			0x00, 0x00, 0x00, 0xFF,
			0xFF, 0x00, 0x00, 0x00,
		},
	})
	require.NoError(t, err)

	rgba, ok := img.Image().(*image.RGBA)
	require.True(t, ok)
	assert.Equal(t, color.RGBA{0, 0, 0, 255}, rgba.RGBAAt(0, 0))
	assert.Equal(t, color.RGBA{0, 255, 255, 255}, rgba.RGBAAt(1, 0))
}

func TestDecoder_DecodeCMYKStdlibConversionMode(t *testing.T) {
	d := NewDecoder()

	img, err := d.Decode(&domainimage.ImageData{
		Filter:             domainimage.FilterNone,
		Data:               []byte{0x00, 0x00, 0x00, 0xFF, 0xFF, 0x00, 0x00, 0x00},
		Width:              2,
		Height:             1,
		BitsPerComponent:   8,
		ColorSpace:         domainimage.ColorSpaceDeviceCMYK,
		CMYKConversionMode: domainimage.CMYKConversionModeStdlib,
	})
	require.NoError(t, err)

	rgba, ok := img.Image().(*image.RGBA)
	require.True(t, ok)
	assert.Equal(t, color.RGBA{0, 0, 0, 255}, rgba.RGBAAt(0, 0))
	assert.Equal(t, color.RGBA{0, 255, 255, 255}, rgba.RGBAAt(1, 0))
}

func TestDecoder_DecodeCMYKHybrid75ConversionMode(t *testing.T) {
	d := NewDecoder()

	defaultImg, err := d.Decode(&domainimage.ImageData{
		Filter:           domainimage.FilterNone,
		Data:             []byte{0x80, 0x10, 0x20, 0x30},
		Width:            1,
		Height:           1,
		BitsPerComponent: 8,
		ColorSpace:       domainimage.ColorSpaceDeviceCMYK,
	})
	require.NoError(t, err)

	simpleImg, err := d.Decode(&domainimage.ImageData{
		Filter:             domainimage.FilterNone,
		Data:               []byte{0x80, 0x10, 0x20, 0x30},
		Width:              1,
		Height:             1,
		BitsPerComponent:   8,
		ColorSpace:         domainimage.ColorSpaceDeviceCMYK,
		CMYKConversionMode: domainimage.CMYKConversionModeSimpleSubtractive,
	})
	require.NoError(t, err)

	hybridImg, err := d.Decode(&domainimage.ImageData{
		Filter:             domainimage.FilterNone,
		Data:               []byte{0x80, 0x10, 0x20, 0x30},
		Width:              1,
		Height:             1,
		BitsPerComponent:   8,
		ColorSpace:         domainimage.ColorSpaceDeviceCMYK,
		CMYKConversionMode: domainimage.CMYKConversionModeHybrid75,
	})
	require.NoError(t, err)

	defaultRGBA := defaultImg.Image().(*image.RGBA).RGBAAt(0, 0)
	simpleRGBA := simpleImg.Image().(*image.RGBA).RGBAAt(0, 0)
	hybridRGBA := hybridImg.Image().(*image.RGBA).RGBAAt(0, 0)

	assert.Equal(t, uint8(255), hybridRGBA.A)
	assert.InDelta(t, blendChannel(defaultRGBA.R, simpleRGBA.R, 0.75), hybridRGBA.R, 0)
	assert.InDelta(t, blendChannel(defaultRGBA.G, simpleRGBA.G, 0.75), hybridRGBA.G, 0)
	assert.InDelta(t, blendChannel(defaultRGBA.B, simpleRGBA.B, 0.75), hybridRGBA.B, 0)
}

func TestDecoder_DecodeIndexedCMYKStdlibConversionMode(t *testing.T) {
	d := NewDecoder()

	img, err := d.Decode(&domainimage.ImageData{
		Filter:             domainimage.FilterNone,
		Data:               []byte{0x00, 0x01},
		Width:              2,
		Height:             1,
		BitsPerComponent:   8,
		ColorSpace:         domainimage.ColorSpaceIndexed,
		IndexedBase:        domainimage.ColorSpaceDeviceCMYK,
		CMYKConversionMode: domainimage.CMYKConversionModeStdlib,
		IndexedLookup: []byte{
			0x00, 0x00, 0x00, 0xFF,
			0xFF, 0x00, 0x00, 0x00,
		},
	})
	require.NoError(t, err)

	rgba, ok := img.Image().(*image.RGBA)
	require.True(t, ok)
	assert.Equal(t, color.RGBA{0, 0, 0, 255}, rgba.RGBAAt(0, 0))
	assert.Equal(t, color.RGBA{0, 255, 255, 255}, rgba.RGBAAt(1, 0))
}

func TestDecoder_DecodeIndexedCMYKHybrid75ConversionMode(t *testing.T) {
	d := NewDecoder()

	defaultImg, err := d.Decode(&domainimage.ImageData{
		Filter:           domainimage.FilterNone,
		Data:             []byte{0x00},
		Width:            1,
		Height:           1,
		BitsPerComponent: 8,
		ColorSpace:       domainimage.ColorSpaceIndexed,
		IndexedBase:      domainimage.ColorSpaceDeviceCMYK,
		IndexedLookup: []byte{
			0x80, 0x10, 0x20, 0x30,
		},
	})
	require.NoError(t, err)

	simpleImg, err := d.Decode(&domainimage.ImageData{
		Filter:             domainimage.FilterNone,
		Data:               []byte{0x00},
		Width:              1,
		Height:             1,
		BitsPerComponent:   8,
		ColorSpace:         domainimage.ColorSpaceIndexed,
		IndexedBase:        domainimage.ColorSpaceDeviceCMYK,
		CMYKConversionMode: domainimage.CMYKConversionModeSimpleSubtractive,
		IndexedLookup: []byte{
			0x80, 0x10, 0x20, 0x30,
		},
	})
	require.NoError(t, err)

	hybridImg, err := d.Decode(&domainimage.ImageData{
		Filter:             domainimage.FilterNone,
		Data:               []byte{0x00},
		Width:              1,
		Height:             1,
		BitsPerComponent:   8,
		ColorSpace:         domainimage.ColorSpaceIndexed,
		IndexedBase:        domainimage.ColorSpaceDeviceCMYK,
		CMYKConversionMode: domainimage.CMYKConversionModeHybrid75,
		IndexedLookup: []byte{
			0x80, 0x10, 0x20, 0x30,
		},
	})
	require.NoError(t, err)

	defaultRGBA := defaultImg.Image().(*image.RGBA).RGBAAt(0, 0)
	simpleRGBA := simpleImg.Image().(*image.RGBA).RGBAAt(0, 0)
	hybridRGBA := hybridImg.Image().(*image.RGBA).RGBAAt(0, 0)

	assert.Equal(t, uint8(255), hybridRGBA.A)
	assert.InDelta(t, blendChannel(defaultRGBA.R, simpleRGBA.R, 0.75), hybridRGBA.R, 0)
	assert.InDelta(t, blendChannel(defaultRGBA.G, simpleRGBA.G, 0.75), hybridRGBA.G, 0)
	assert.InDelta(t, blendChannel(defaultRGBA.B, simpleRGBA.B, 0.75), hybridRGBA.B, 0)
}

func TestDecoder_ApplyDecodeTransforms(t *testing.T) {
	d := NewDecoder()
	img, err := d.Decode(&domainimage.ImageData{
		Filter:           domainimage.FilterNone,
		Data:             []byte{0x00, 0x80},
		Width:            1,
		Height:           2,
		BitsPerComponent: 8,
		Decode:           []float64{1, 0},
		ColorSpace:       domainimage.ColorSpaceDeviceGray,
	})
	require.NoError(t, err)

	gray, ok := img.Image().(*image.Gray)
	require.True(t, ok)
	assert.Equal(t, uint8(255), gray.GrayAt(0, 0).Y)
	assert.Equal(t, uint8(127), gray.GrayAt(0, 1).Y)
}

func TestDecoder_ApplyDecodeTransformsForNon8BPC(t *testing.T) {
	d := NewDecoder()
	img, err := d.Decode(&domainimage.ImageData{
		Filter:           domainimage.FilterNone,
		Data:             []byte{0b10000000, 0x00},
		Width:            1,
		Height:           2,
		BitsPerComponent: 1,
		Decode:           []float64{1, 0},
		ColorSpace:       domainimage.ColorSpaceDeviceGray,
	})
	require.NoError(t, err)

	gray, ok := img.Image().(*image.Gray)
	require.True(t, ok)
	assert.Equal(t, uint8(0), gray.GrayAt(0, 0).Y)
	assert.Equal(t, uint8(255), gray.GrayAt(0, 1).Y)
}

func TestDecodeArrayClampsOutOfRange(t *testing.T) {
	value := decodeArray(32767, []float64{255, 0}, 255)
	assert.Equal(t, uint8(0), clampToByte(value, false))
}

func TestApplyCurveToBytePreservesEndpoints(t *testing.T) {
	curve := func(v float64) float64 {
		return 0.08 + v*0.5
	}

	assert.Equal(t, uint8(0), applyCurveToByte(0, curve))
	assert.Equal(t, uint8(255), applyCurveToByte(255, curve))
	assert.NotEqual(t, uint8(128), applyCurveToByte(128, curve))
}

func TestDecoder_RegisterCustomDecoder(t *testing.T) {
	d := NewDecoder()
	stub := &stubDecoder{}
	d.RegisterDecoder(domainimage.FilterDCT, stub)

	img, err := d.Decode(&domainimage.ImageData{
		Filter:           domainimage.FilterDCT,
		Data:             []byte("4142"),
		Width:            1,
		Height:           1,
		BitsPerComponent: 8,
		ColorSpace:       domainimage.ColorSpaceDeviceRGB,
	})
	require.NoError(t, err)
	_, ok := img.Image().(*image.RGBA)
	require.True(t, ok)
	assert.True(t, stub.wasUsed)
}

func TestDecoder_DecodeLZWAndASCII85Branches(t *testing.T) {
	d := NewDecoder()

	var compressed bytes.Buffer
	w := lzw.NewWriter(&compressed, lzw.MSB, 8)
	_, err := w.Write([]byte("LZW"))
	require.NoError(t, err)
	require.NoError(t, w.Close())

	lzwDecoded, err := d.decodeLZW(compressed.Bytes())
	require.NoError(t, err)
	assert.Equal(t, []byte("LZW"), lzwDecoded)

	_, err = d.decodeLZW(nil)
	require.NoError(t, err)

	var lsbCompressed bytes.Buffer
	lsbWriter := lzw.NewWriter(&lsbCompressed, lzw.LSB, 8)
	_, err = lsbWriter.Write([]byte("LSBFALLBACK"))
	require.NoError(t, err)
	require.NoError(t, lsbWriter.Close())

	lsbDecoded, err := d.decodeLZW(lsbCompressed.Bytes())
	require.NoError(t, err)
	assert.Equal(t, []byte("LSBFALLBACK"), lsbDecoded)

	ascii85Decoded, err := d.decodeASCII85([]byte("!!!!!~>"))
	require.NoError(t, err)
	assert.Equal(t, []byte{0, 0, 0, 0}, ascii85Decoded)

	ascii85Decoded, err = d.decodeASCII85([]byte("!!!!"))
	require.NoError(t, err)
	assert.Len(t, ascii85Decoded, 3)

	ascii85Decoded, err = d.decodeASCII85([]byte("<~\n!!!!!\n~>"))
	require.NoError(t, err)
	assert.Equal(t, []byte{0, 0, 0, 0}, ascii85Decoded)

	_, err = d.decodeASCII85([]byte("{"))
	require.Error(t, err)
	_, err = d.decodeASCII85(nil)
	require.Error(t, err)
}

func TestDecoder_DecodeRGBImageNon8BPC(t *testing.T) {
	d := NewDecoder()
	img, err := d.decodeRGBImage([]byte{0b11100000}, 1, 1, 1, 1, nil, nil)
	require.NoError(t, err)
	assert.Equal(t, color.RGBA{R: 255, G: 255, B: 255, A: 255}, img.RGBAAt(0, 0))
}

func jpegTestData(t *testing.T) []byte {
	t.Helper()
	rgb := image.NewRGBA(image.Rect(0, 0, 1, 1))
	rgb.SetRGBA(0, 0, color.RGBA{R: 1, G: 2, B: 3, A: 255})

	var encoded bytes.Buffer
	err := jpeg.Encode(&encoded, rgb, &jpeg.Options{Quality: 80})
	require.NoError(t, err)

	return encoded.Bytes()
}

func jpegTestGrayData(t *testing.T) []byte {
	t.Helper()
	gray := image.NewGray(image.Rect(0, 0, 1, 1))
	gray.SetGray(0, 0, color.Gray{Y: 200})

	var encoded bytes.Buffer
	err := jpeg.Encode(&encoded, gray, &jpeg.Options{Quality: 80})
	require.NoError(t, err)

	return encoded.Bytes()
}
